# Generated by Django 4.2.16 on 2024-12-28 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "класс",
                "verbose_name_plural": "классы",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="уникальный идентификатор",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="включен"),
                ),
                ("signal", models.BooleanField(default=False, verbose_name="сигнал")),
                (
                    "work",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_work.work",
                        verbose_name="класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "компьютер",
                "verbose_name_plural": "компьютеры",
                "ordering": ("name",),
            },
        ),
    ]
